#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
if [[ ! -x "$ROOT/build/install/simple-ide/bin/simple-ide" ]]; then
  "$ROOT/build.sh"
fi
JAVA_HOME="/usr/lib/jvm/java-1.17.0-openjdk-amd64" exec "$ROOT/build/install/simple-ide/bin/simple-ide" "$@"
